"""empty message

Revision ID: c2b948547744
Revises: 
Create Date: 2024-05-06 21:16:43.353299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b948547744'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communication', 'vacancy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('communication', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'communication', 'vacancies', ['vacancy_id'], ['id'])
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'descriprion',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'descriprion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'communication', type_='foreignkey')
    op.alter_column('communication', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('communication', 'vacancy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
