"""empty message

Revision ID: c7694f9e0086
Revises: b8cbcd375a51
Create Date: 2024-05-11 21:00:31.807115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7694f9e0086'
down_revision: Union[str, None] = 'b8cbcd375a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
